# [1] add the source to the top of your Podfile.
source 'https://bitbucket.org/sencyai/ios_sdks_release.git'
source 'https://bitbucket.org/sencyai/ios_sdks_dev.git'
source 'https://github.com/CocoaPods/Specs.git'

workspace 'SMKitUIDemo.xcworkspace'

#[2] add the pod to your target
target 'SMKitDemo' do
  use_frameworks!
#  pod 'SMKitDev' , '0.2.7'
end

#[3] add post_install hooks
#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
#      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
#      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.5'
#    end
#  end
#end

